# Generated by Django 4.2.30 on 2026-08-09 21:00

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=200)),
                ('company', models.CharField(max_length=200)),
                ('company_domain', models.CharField(blank=True, max_length=200)),
                ('location', models.CharField(max_length=200)),
                ('experience_required', models.CharField(blank=True, max_length=100)),
                ('source', models.CharField(choices=[('naukri', 'Naukri'), ('internshala', 'Internshala'), ('indeed', 'Indeed'), ('instahyre', 'Instahyre')], max_length=50)),
                ('source_url', models.URLField(max_length=500)),
                ('jd_text', models.TextField()),
                ('relevancy_score', models.FloatField(default=0.0)),
                ('skills_extracted', models.JSONField(default=list)),
                ('posted_at', models.DateTimeField(blank=True, null=True)),
                ('fetched_at', models.DateTimeField(auto_now_add=True)),
                ('dedup_hash', models.CharField(max_length=64, unique=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['-relevancy_score', '-posted_at'],
            },
        ),
        migrations.CreateModel(
            name='SearchQuery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('query', models.CharField(max_length=200)),
                ('location', models.CharField(max_length=200)),
                ('last_scraped_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name_plural': 'Search Queries',
                'unique_together': {('query', 'location')},
            },
        ),
    ]
