# Generated by Django 4.2.30 on 2026-08-15 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='experience_required',
            field=models.CharField(blank=True, max_length=500),
        ),
    ]
