# Generated by Django 4.2.30 on 2026-08-10 09:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('jobs', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('email', models.EmailField(max_length=254)),
                ('first_name', models.CharField(blank=True, max_length=100)),
                ('last_name', models.CharField(blank=True, max_length=100)),
                ('title', models.CharField(blank=True, max_length=200)),
                ('department', models.CharField(blank=True, max_length=100)),
                ('source', models.CharField(choices=[('jd_extract', 'JD Extract'), ('hunter', 'Hunter.io'), ('smtp_pattern', 'SMTP Pattern'), ('manual', 'Manual')], max_length=50)),
                ('smtp_status', models.CharField(choices=[('valid', 'Valid'), ('risky', 'Risky'), ('catch_all', 'Catch All'), ('not_found', 'Not Found'), ('unverified', 'Unverified')], default='unverified', max_length=50)),
                ('is_catch_all', models.BooleanField(default=False)),
                ('confidence_score', models.FloatField(default=0.0)),
                ('verified_at', models.DateTimeField(blank=True, null=True)),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contacts', to='jobs.job')),
            ],
            options={
                'ordering': ['-confidence_score', '-verified_at'],
                'unique_together': {('job', 'email')},
            },
        ),
        migrations.CreateModel(
            name='OutreachLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('email_subject', models.CharField(max_length=500)),
                ('email_body', models.TextField()),
                ('gmail_message_id', models.CharField(blank=True, max_length=200)),
                ('status', models.CharField(choices=[('queued', 'Queued'), ('sent', 'Sent'), ('failed', 'Failed')], default='queued', max_length=50)),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
                ('error_message', models.TextField(blank=True)),
                ('contact', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='outreach.contact')),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='jobs.job')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
